services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - POSTGRES_DB=music
      - POSTGRES_USER=${LOGIN}
      - POSTGRES_PASSWORD=${PASSWORD}
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
